DROP TABLE FUNCIONARIO;
CREATE TABLE FUNCIONARIO ( -- CRIAÇÃO DA TABELA FUNCIONARIO
    CPF_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNCIONARIO VARCHAR(100),
    CARGO_FUNCIONARIO VARCHAR(100),
    SALARIO_FUNCIONARIO FLOAT,
    DATA_ADMISSAO_FUNCIONARIO DATE,
    ID_SETOR INT,
    FOREIGN KEY (ID_SETOR) REFERENCES SETORES(ID_SETOR)
)


DROP TABLE SETORES;
CREATE TABLE SETORES ( -- CRIAÇÃO DA TABELA SETORES
    ID_SETOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SETOR VARCHAR(100),
    LOCALIZACAO_SETOR VARCHAR(100)
)


CREATE TABLE PRODUTOS ( -- CRIAÇÃO DA TABELA PRODUTOS
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(80),
    PRECO_PRODUTO FLOAT,
    QUANTIDADE_PRODUTO INT,
    DESCRICAO_PRODUTO TEXT
)

CREATE TABLE CATEGORIAS ( -- CRIAÇÃO DA TABELA CATEGORIAS
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(120)
)

CREATE TABLE FORNECEDORES ( -- CRIAÇÃO DA TABELA FORNECEDORES
    CNPJ_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    TELEFONE_FORNECEDOR VARCHAR(100),
    CIDADE_FORNECEDOR VARCHAR(200)
)

CREATE TABLE ORDENS_PRODUCAO ( -- CRIAÇÃO DA TABELA ORDENS_PRODUCAO
    DATA_PRODUCAO DATE,
    QUANTIDADE_PRODUZIDA INT,
    STATUS_PRODUCAO VARCHAR(90),
    TEMPO_ESTIMADO_PRODUCAO INT,
    TEMPO_REAL_PRODUCAO INT
)

CREATE TABLE CONTROLE_QUALIDADE( -- CRIAÇÃO DA TABELA CONTROLE_QUALIDADE
    DATA_DA_INSPECAO DATE,
    RESULTADO_INSPECAO VARCHAR(100),
    OBSERVACOES_TECNICAS TEXT
)

 