INSERT INTO SETORES (ID_SETOR, NOME_SETOR, LOCALIZACAO_SETOR) VALUES
(1, 'USINAGEM', ''


INSERT INTO FUNCIONARIOS (CPF_FUNCIONARIO,NOME_FUNCIONARIO, CARGO_FUNCIONARIO, SALARIO_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, ID_SETOR))