INSERT INTO SETORES (ID_SETOR, NOME_SETOR, LOCALIZACAO_SETOR) 
VALUES
(1, 'USINAGEM', '110'),
(2, 'SOLDAGEM', '111'),
(3, 'PINTURA', '112'),
(4, 'MONTAGEM', '113'),
(5, 'QUALIDADE', '114');

INSERT INTO FUNCIONARIO (CPF_FUNCIONARIO, NOME_FUNCIONARIO, CARGO_FUNCIONARIO, SALARIO_FUNCIONARIO, DATA_ADMISSAO_FUNCIONARIO, ID_SETOR)
VALUES