CREATE TABLE FUNCIONARIO (
    CPF_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNCIONARIO VARCHAR(255),
    CARGO_FUNCIONARIO VARCHAR(255),
    SALARIO_FUNCIONARIO FLOAT,
    DATA_ADMISSAO_FUNCIONARIO DATE
)