CREATE TABLE FUNCIONARIO ( -- CRIAÇÃO DA TABELA FUNCIONARIO
    CPF_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNCIONARIO VARCHAR(100),
    CARGO_FUNCIONARIO VARCHAR(100),
    SALARIO_FUNCIONARIO FLOAT,
    DATA_ADMISSAO_FUNCIONARIO DATE
)

CREATE TABLE SETORES ( -- CRIAÇÃO DA TABELA SETORES
    ID_SETOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SETOR VARCHAR(100)
    LOCALIZACAO_SETOR VARCHAR(100),
)

CREATE TABLE PRODUTOS ( -- CRIAÇÃO DA TABELA PRODUTOS
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100),
    PRECO_PRODUTO FLOAT,
    QUANTIDADE_PRODUTO INT
)